import { app } from "@azure/functions";
import { getLearningAccess } from "../lib/learningAccess.js";
import { listContent, reviewSummary, setReviewStatus } from "../lib/contentStore.js";

// Curriculum content is generated by a model and shown to children, so an
// administrator can read it and approve or reject it before it is served.
// Reviewing is administrator-only: it decides what every learner sees.
app.http("review", {
  methods: ["GET", "POST"],
  authLevel: "anonymous",
  route: "review/{action?}",
  handler: async (request, context) => {
    try {
      const access = await getLearningAccess(request);
      if (!access.admin) {
        return { status: 403, jsonBody: { error: "Only an administrator can review curriculum content." } };
      }

      if (request.method === "GET") {
        if (request.params.action === "summary") {
          return { jsonBody: await reviewSummary() };
        }
        const rows = await listContent({
          type: request.query.get("type") ?? undefined,
          year: request.query.get("year") ?? undefined,
          subject: request.query.get("subject") ?? undefined,
          status: request.query.get("status") ?? "pending",
          limit: Math.max(1, Math.min(100, Number(request.query.get("limit")) || 25)),
          withPayload: true,
        });
        return { jsonBody: { rows } };
      }

      const body = await request.json();
      const { topicId, rowKey, status } = body;
      if (typeof topicId !== "string" || typeof rowKey !== "string") {
        return { status: 400, jsonBody: { error: "A topic and row reference are required." } };
      }
      const result = await setReviewStatus(topicId, rowKey, status, access.email);
      if (!result) return { status: 404, jsonBody: { error: "That content could not be found, or the status is not valid." } };
      return { jsonBody: result };
    } catch (error) {
      context.error("Content review failure", error.message);
      return { status: 503, jsonBody: { error: "Content review is unavailable right now." } };
    }
  },
});
